### ISSUE TITLE
Audit plugin issue

### ISSUE THREAD

**Issue by yrsurya** [jenkinsci/audit2db-plugin#16]
Hi, I am trying to use this plugin as I need full audit reports from jenkins but am getting following error while running jobs. Connection was succesfull and even created tables in database

ERROR: Build step failed with exception
java.lang.NullPointerException
        at org.jenkins.plugins.audit2db.internal.DbAuditPublisherImpl.perform(DbAuditPublisherImpl.java:110)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
        at hudson.model.Build$BuildExecution.cleanUp(Build.java:195)
        at hudson.model.Run.execute(Run.java:1788)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:98)
        at hudson.model.Executor.run(Executor.java:410)
Build step 'Audit job info to Database' marked build as failure
Finished: FAILURE

**Comment by mugar97** [comment]
Hi, I just got the same error
Any idea about it?
